modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="tfc_iciclesmelt"
version="0.0.1"
displayName="TFC Icicles Melt"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png"
credits="Thanks to me for making this lol"
authors="Sarcly"
description='''
I got annoyed that icicles dont melt with light sources like snow layers and ice blocks do. So I fixed it.
'''

[[dependencies.tfc_iciclesmelt]]
	modId="tfc"
	mandatory=true
	versionRange="[2.2.23,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.tfc_iciclesmelt]]
    modId="forge"
    mandatory=true
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.tfc_iciclesmelt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
